//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDPL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shiksha.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcademicYearName already exists!.
        /// </summary>
        public static string lbl_AcademicYearExist {
            get {
                return ResourceManager.GetString("lbl_AcademicYearExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcademicYear Id is required !.
        /// </summary>
        public static string lbl_academicYearIdRequired {
            get {
                return ResourceManager.GetString("lbl_academicYearIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year Not Inserted !.
        /// </summary>
        public static string lbl_AcademicYearNotInserted {
            get {
                return ResourceManager.GetString("lbl_AcademicYearNotInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Deleted.
        /// </summary>
        public static string lbl_accountDeleted {
            get {
                return ResourceManager.GetString("lbl_accountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Disabled.
        /// </summary>
        public static string lbl_accountDisabled {
            get {
                return ResourceManager.GetString("lbl_accountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance is already taken !.
        /// </summary>
        public static string lbl_Attendance_Taken {
            get {
                return ResourceManager.GetString("lbl_Attendance_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student added after marking an attendance !.
        /// </summary>
        public static string lbl_AttendanceMarkedBeforeStudentAdded {
            get {
                return ResourceManager.GetString("lbl_AttendanceMarkedBeforeStudentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string lbl_Cap_information {
            get {
                return ResourceManager.GetString("lbl_Cap_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string lbl_Cap_success {
            get {
                return ResourceManager.GetString("lbl_Cap_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term and grade&apos;s start and end date is not provided by school !.
        /// </summary>
        public static string lbl_classCreateInvalid {
            get {
                return ResourceManager.GetString("lbl_classCreateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name Already Exists !.
        /// </summary>
        public static string lbl_ClassNameAlreadyExists {
            get {
                return ResourceManager.GetString("lbl_ClassNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class name is already exist !.
        /// </summary>
        public static string lbl_ClassNameExist {
            get {
                return ResourceManager.GetString("lbl_ClassNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string lbl_confirmpassword {
            get {
                return ResourceManager.GetString("lbl_confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum disabled !.
        /// </summary>
        public static string lbl_CurriculumDisabled {
            get {
                return ResourceManager.GetString("lbl_CurriculumDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum enabled !.
        /// </summary>
        public static string lbl_CurriculumEnabled {
            get {
                return ResourceManager.GetString("lbl_CurriculumEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records fetched..
        /// </summary>
        public static string lbl_DataFetched {
            get {
                return ResourceManager.GetString("lbl_DataFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Fetched !.
        /// </summary>
        public static string lbl_DataNotFetched {
            get {
                return ResourceManager.GetString("lbl_DataNotFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default attendance already marked !.
        /// </summary>
        public static string lbl_default_attendance_already_marked {
            get {
                return ResourceManager.GetString("lbl_default_attendance_already_marked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default attendance not marked yet !.
        /// </summary>
        public static string lbl_default_attendanceError {
            get {
                return ResourceManager.GetString("lbl_default_attendanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device id is Different.
        /// </summary>
        public static string lbl_deviceId {
            get {
                return ResourceManager.GetString("lbl_deviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name already exist !.
        /// </summary>
        public static string lbl_domainNameExist {
            get {
                return ResourceManager.GetString("lbl_domainNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name not found !.
        /// </summary>
        public static string lbl_domainNameNotFound {
            get {
                return ResourceManager.GetString("lbl_domainNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string lbl_emailAddress {
            get {
                return ResourceManager.GetString("lbl_emailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id is already in use..
        /// </summary>
        public static string lbl_emilIdInUse {
            get {
                return ResourceManager.GetString("lbl_emilIdInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Id is empty!.
        /// </summary>
        public static string lbl_emptyDeviceID {
            get {
                return ResourceManager.GetString("lbl_emptyDeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry ID is already registered !.
        /// </summary>
        public static string lbl_EnquiryID_not_unique {
            get {
                return ResourceManager.GetString("lbl_EnquiryID_not_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string lbl_error {
            get {
                return ResourceManager.GetString("lbl_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone Number ! (only + sign and numbers are valid).
        /// </summary>
        public static string lbl_excel_invalid_phone_number {
            get {
                return ResourceManager.GetString("lbl_excel_invalid_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bulk request file is now successfully uploaded. In 20min all requests will be sent, so check in Pending Request page after 20min for status..
        /// </summary>
        public static string lbl_ExcelSuccess {
            get {
                return ResourceManager.GetString("lbl_ExcelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception!.
        /// </summary>
        public static string lbl_exception {
            get {
                return ResourceManager.GetString("lbl_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory data is empty !.
        /// </summary>
        public static string lbl_excle_mandatory_empty {
            get {
                return ResourceManager.GetString("lbl_excle_mandatory_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        public static string lbl_exportToExcel {
            get {
                return ResourceManager.GetString("lbl_exportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father account cannot be created since this email id is already used for mother.
        /// </summary>
        public static string lbl_FatherEmail {
            get {
                return ResourceManager.GetString("lbl_FatherEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Special character in Fathername.
        /// </summary>
        public static string lbl_FatherName {
            get {
                return ResourceManager.GetString("lbl_FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s).
        /// </summary>
        public static string lbl_files {
            get {
                return ResourceManager.GetString("lbl_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Special character in Firstname.
        /// </summary>
        public static string lbl_FirstName {
            get {
                return ResourceManager.GetString("lbl_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Id is required !.
        /// </summary>
        public static string lbl_gradeIdRequired {
            get {
                return ResourceManager.GetString("lbl_gradeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade name already exist !.
        /// </summary>
        public static string lbl_GradeNameExist {
            get {
                return ResourceManager.GetString("lbl_GradeNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade name not found !.
        /// </summary>
        public static string lbl_GradeNameNotFound {
            get {
                return ResourceManager.GetString("lbl_GradeNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Not Inserted !.
        /// </summary>
        public static string lbl_GradeNotInserted {
            get {
                return ResourceManager.GetString("lbl_GradeNotInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not saved !.
        /// </summary>
        public static string lbl_image_not_saved {
            get {
                return ResourceManager.GetString("lbl_image_not_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string lbl_in {
            get {
                return ResourceManager.GetString("lbl_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect domain name !.
        /// </summary>
        public static string lbl_IncorrectDomainName {
            get {
                return ResourceManager.GetString("lbl_IncorrectDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect grade name !.
        /// </summary>
        public static string lbl_IncorrectGradeName {
            get {
                return ResourceManager.GetString("lbl_IncorrectGradeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string lbl_input {
            get {
                return ResourceManager.GetString("lbl_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error Occurred!.
        /// </summary>
        public static string lbl_internalServerErrorOccurred {
            get {
                return ResourceManager.GetString("lbl_internalServerErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string lbl_invalid {
            get {
                return ResourceManager.GetString("lbl_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ScanTime.
        /// </summary>
        public static string lbl_Invalid_ScanTime {
            get {
                return ResourceManager.GetString("lbl_Invalid_ScanTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input Details !.
        /// </summary>
        public static string lbl_invalidInputs {
            get {
                return ResourceManager.GetString("lbl_invalidInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiosk Id not found!.
        /// </summary>
        public static string lbl_InvalidKioskID {
            get {
                return ResourceManager.GetString("lbl_InvalidKioskID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Validation Failed..
        /// </summary>
        public static string lbl_invalidToken {
            get {
                return ResourceManager.GetString("lbl_invalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL !.
        /// </summary>
        public static string lbl_invalidURL {
            get {
                return ResourceManager.GetString("lbl_invalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice For Student Fees.
        /// </summary>
        public static string lbl_Invoice_Sub {
            get {
                return ResourceManager.GetString("lbl_Invoice_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Special character in Lastname.
        /// </summary>
        public static string lbl_LastName {
            get {
                return ResourceManager.GetString("lbl_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson Plan Disabled !.
        /// </summary>
        public static string lbl_LessonPlanDisabled {
            get {
                return ResourceManager.GetString("lbl_LessonPlanDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson Plan Enabled !.
        /// </summary>
        public static string lbl_LessonPlanEnabled {
            get {
                return ResourceManager.GetString("lbl_LessonPlanEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Objective Name Already Exist !.
        /// </summary>
        public static string lbl_LOExist {
            get {
                return ResourceManager.GetString("lbl_LOExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string lbl_log {
            get {
                return ResourceManager.GetString("lbl_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother account cannot be created since this email id is already used for father.
        /// </summary>
        public static string lbl_MotherEmail {
            get {
                return ResourceManager.GetString("lbl_MotherEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Special character in Mothername.
        /// </summary>
        public static string lbl_MotherName {
            get {
                return ResourceManager.GetString("lbl_MotherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year Not Saved.
        /// </summary>
        public static string lbl_msg_academicYearNotSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_academicYearNotSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year Not Updated.
        /// </summary>
        public static string lbl_msg_academicYearNotUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_academicYearNotUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year Saved Successfully.
        /// </summary>
        public static string lbl_msg_academicYearSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_academicYearSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year Updated Successfully.
        /// </summary>
        public static string lbl_msg_academicYearUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_academicYearUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Does Not Exist.
        /// </summary>
        public static string lbl_msg_accountDoesNotExit {
            get {
                return ResourceManager.GetString("lbl_msg_accountDoesNotExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not activated.
        /// </summary>
        public static string lbl_msg_accountNotActivated {
            get {
                return ResourceManager.GetString("lbl_msg_accountNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Not Saved.
        /// </summary>
        public static string lbl_msg_classNotSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_classNotSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Not Updated.
        /// </summary>
        public static string lbl_msg_classNotUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_classNotUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Saved Successfully.
        /// </summary>
        public static string lbl_msg_classSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_classSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Updated Successfully.
        /// </summary>
        public static string lbl_msg_classUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_classUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Not Saved !.
        /// </summary>
        public static string lbl_msg_dataNotSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_dataNotSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved Successfully.
        /// </summary>
        public static string lbl_msg_dataSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_dataSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Failed.
        /// </summary>
        public static string lbl_msg_emailAddressFailed {
            get {
                return ResourceManager.GetString("lbl_msg_emailAddressFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Required.
        /// </summary>
        public static string lbl_msg_eMailAddressRequired {
            get {
                return ResourceManager.GetString("lbl_msg_eMailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email and Password Required.
        /// </summary>
        public static string lbl_msg_emailPasswordRequired {
            get {
                return ResourceManager.GetString("lbl_msg_emailPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email and Refresh Token Required !.
        /// </summary>
        public static string lbl_msg_emailRefreshTokenRequired {
            get {
                return ResourceManager.GetString("lbl_msg_emailRefreshTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Not Saved.
        /// </summary>
        public static string lbl_msg_gradeNotSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_gradeNotSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Not Updated.
        /// </summary>
        public static string lbl_msg_gradeNotUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_gradeNotUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Saved Successfully.
        /// </summary>
        public static string lbl_msg_gradeSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_gradeSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Updated Successfully.
        /// </summary>
        public static string lbl_msg_gradeUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_gradeUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Details !.
        /// </summary>
        public static string lbl_msg_IncompleteDetails {
            get {
                return ResourceManager.GetString("lbl_msg_IncompleteDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error Occurred.
        /// </summary>
        public static string lbl_msg_internalServerErrorOccurred {
            get {
                return ResourceManager.GetString("lbl_msg_internalServerErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string lbl_msg_invalidEmailAddress {
            get {
                return ResourceManager.GetString("lbl_msg_invalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address and Password.
        /// </summary>
        public static string lbl_msg_invalidEmailAddressPassword {
            get {
                return ResourceManager.GetString("lbl_msg_invalidEmailAddressPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email ID OR Password.
        /// </summary>
        public static string lbl_msg_invalidEmpIdAddressPassword {
            get {
                return ResourceManager.GetString("lbl_msg_invalidEmpIdAddressPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Passowrd.
        /// </summary>
        public static string lbl_msg_invalidPassowrd {
            get {
                return ResourceManager.GetString("lbl_msg_invalidPassowrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl_msg_loginFailed.
        /// </summary>
        public static string lbl_msg_loginFailed {
            get {
                return ResourceManager.GetString("lbl_msg_loginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change email sent.
        /// </summary>
        public static string lbl_msg_passwordChangeEmail {
            get {
                return ResourceManager.GetString("lbl_msg_passwordChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set Grades and Terms for the creation of Class !.
        /// </summary>
        public static string lbl_msg_PleaseContactYourSchoolAdminToSetTermDates {
            get {
                return ResourceManager.GetString("lbl_msg_PleaseContactYourSchoolAdminToSetTermDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchoolHQ Not Saved.
        /// </summary>
        public static string lbl_msg_schoolHQNotSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_schoolHQNotSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchoolHQ Not Updated.
        /// </summary>
        public static string lbl_msg_schoolHQNotUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_schoolHQNotUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchoolHQ Saved Successfully.
        /// </summary>
        public static string lbl_msg_schoolHQSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_schoolHQSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchoolHQ Updated Successfully.
        /// </summary>
        public static string lbl_msg_schoolHQUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_schoolHQUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School login not generated..
        /// </summary>
        public static string lbl_msg_SchoolLoginNotGenerated {
            get {
                return ResourceManager.GetString("lbl_msg_SchoolLoginNotGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Not Saved.
        /// </summary>
        public static string lbl_msg_schoolNotSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_schoolNotSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Not Updated.
        /// </summary>
        public static string lbl_msg_schoolNotUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_schoolNotUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Saved Successfully.
        /// </summary>
        public static string lbl_msg_schoolSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_schoolSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Updated Successfully.
        /// </summary>
        public static string lbl_msg_schoolUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_schoolUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Not Saved.
        /// </summary>
        public static string lbl_msg_studentNotSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_studentNotSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Not Updated.
        /// </summary>
        public static string lbl_msg_studentNotUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_studentNotUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Saved Successfully.
        /// </summary>
        public static string lbl_msg_studentSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_studentSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Updated Successfully.
        /// </summary>
        public static string lbl_msg_studentUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_studentUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Not Saved.
        /// </summary>
        public static string lbl_msg_teacherNotSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_teacherNotSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Not Updated.
        /// </summary>
        public static string lbl_msg_teacherNotUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_teacherNotUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Saved Successfully.
        /// </summary>
        public static string lbl_msg_teacherSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_teacherSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Updated Successfully.
        /// </summary>
        public static string lbl_msg_teacherUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_teacherUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string lbl_new {
            get {
                return ResourceManager.GetString("lbl_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Files Attached.
        /// </summary>
        public static string lbl_noFilesAttached {
            get {
                return ResourceManager.GetString("lbl_noFilesAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found.
        /// </summary>
        public static string lbl_noRecordsFound {
            get {
                return ResourceManager.GetString("lbl_noRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not found..
        /// </summary>
        public static string lbl_Not_Found {
            get {
                return ResourceManager.GetString("lbl_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string lbl_of {
            get {
                return ResourceManager.GetString("lbl_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string lbl_page {
            get {
                return ResourceManager.GetString("lbl_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lbl_password {
            get {
                return ResourceManager.GetString("lbl_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Is Already Exist !.
        /// </summary>
        public static string lbl_phoneNumberIsAlreadyExist {
            get {
                return ResourceManager.GetString("lbl_phoneNumberIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Disabled !.
        /// </summary>
        public static string lbl_PostDisabled {
            get {
                return ResourceManager.GetString("lbl_PostDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post enabled !.
        /// </summary>
        public static string lbl_PostEnabled {
            get {
                return ResourceManager.GetString("lbl_PostEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string lbl_profile {
            get {
                return ResourceManager.GetString("lbl_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Not Promoted !.
        /// </summary>
        public static string lbl_promote_fail {
            get {
                return ResourceManager.GetString("lbl_promote_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Promoted SuccessFully !.
        /// </summary>
        public static string lbl_promote_success {
            get {
                return ResourceManager.GetString("lbl_promote_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string lbl_records {
            get {
                return ResourceManager.GetString("lbl_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Per Page.
        /// </summary>
        public static string lbl_recordsPerPage {
            get {
                return ResourceManager.GetString("lbl_recordsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully!.
        /// </summary>
        public static string lbl_saveSuccessfully {
            get {
                return ResourceManager.GetString("lbl_saveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School created successfully..
        /// </summary>
        public static string lbl_School_Inserted {
            get {
                return ResourceManager.GetString("lbl_School_Inserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School HQ updated successfully..
        /// </summary>
        public static string lbl_School_Updated {
            get {
                return ResourceManager.GetString("lbl_School_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Already Exist !.
        /// </summary>
        public static string lbl_SchoolAlreadyExist {
            get {
                return ResourceManager.GetString("lbl_SchoolAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a school account. Only teacher accounts can login to the app..
        /// </summary>
        public static string lbl_SchoolcannotLogin {
            get {
                return ResourceManager.GetString("lbl_SchoolcannotLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School HQ created successfully..
        /// </summary>
        public static string lbl_SchoolHQ_Inserted {
            get {
                return ResourceManager.GetString("lbl_SchoolHQ_Inserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School HQ updated successfully..
        /// </summary>
        public static string lbl_SchoolHQ_Updated {
            get {
                return ResourceManager.GetString("lbl_SchoolHQ_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchoolSignup.
        /// </summary>
        public static string lbl_SchoolSignup {
            get {
                return ResourceManager.GetString("lbl_SchoolSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lbl_search {
            get {
                return ResourceManager.GetString("lbl_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence Disabled !.
        /// </summary>
        public static string lbl_sentenceDisabled {
            get {
                return ResourceManager.GetString("lbl_sentenceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence Enabled !.
        /// </summary>
        public static string lbl_sentenceEnabled {
            get {
                return ResourceManager.GetString("lbl_sentenceEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Already Exist !.
        /// </summary>
        public static string lbl_StudentAlreadyExist {
            get {
                return ResourceManager.GetString("lbl_StudentAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Already Exist with this External ID.
        /// </summary>
        public static string lbl_StudentAlreadyExistWithThisExternalID {
            get {
                return ResourceManager.GetString("lbl_StudentAlreadyExistWithThisExternalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubDomain Name Already Exist !.
        /// </summary>
        public static string lbl_SubDomainExist {
            get {
                return ResourceManager.GetString("lbl_SubDomainExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string lbl_success {
            get {
                return ResourceManager.GetString("lbl_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Created.
        /// </summary>
        public static string lbl_successfullyCreated {
            get {
                return ResourceManager.GetString("lbl_successfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeacherSignup.
        /// </summary>
        public static string lbl_TeacherSignup {
            get {
                return ResourceManager.GetString("lbl_TeacherSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access unathorised !.
        /// </summary>
        public static string lbl_unauthorised {
            get {
                return ResourceManager.GetString("lbl_unauthorised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already Exist !.
        /// </summary>
        public static string lbl_UserExist {
            get {
                return ResourceManager.GetString("lbl_UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id Or School Id Required !.
        /// </summary>
        public static string lbl_UserIdOrSchoolIdRequired {
            get {
                return ResourceManager.GetString("lbl_UserIdOrSchoolIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id Required !.
        /// </summary>
        public static string lbl_UserIdRequired {
            get {
                return ResourceManager.GetString("lbl_UserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found !.
        /// </summary>
        public static string lbl_UserNotFound {
            get {
                return ResourceManager.GetString("lbl_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version mismatched !.
        /// </summary>
        public static string lbl_versionError {
            get {
                return ResourceManager.GetString("lbl_versionError", resourceCulture);
            }
        }
    }
}
